var nbPages=0;var pagesState=[];var myURLs=new Map();var myPlayer=videojs('player',{});checkOptions();window.onbeforeunload=function(){return""};var toolbarOptions=[['bold','italic','underline','strike'],['blockquote','code-block'],[{'header':1},{'header':2}],[{'list':'ordered'},{'list':'bullet'}],[{'script':'sub'},{'script':'super'}],[{'indent':'-1'},{'indent':'+1'}],[{'direction':'rtl'}],[{'size':['small',!1,'large','huge']}],[{'header':[1,2,3,4,5,6,!1]}],['link','image','video','formula'],[{'color':[]},{'background':[]}],[{'font':[]}],[{'align':[]}],['clean']];var quill=new Quill('#editor',{modules:{imageResize:{displaySize:!0},toolbar:toolbarOptions},theme:'snow'});$(function(){$('[data-toggle="popover"]').popover()})
$(document).on('DOMSubtreeModified',function(){$(function(){$('.fadein').removeClass('fadein')})});function addPage(){nbPages++;var newPage=document.createElement("li");newPage.className="input-group my-1";newPage.style+="position: relative; z-index: 10"
newPage.id="page"+nbPages;newPage.innerHTML='<div class="input-group-prepend">'+'<span class="input-group-text">#'+nbPages+'</span>'+'</div>'+'<input type="text" class="form-control" style="width: 40%" placeholder="Nom de la page" onchange="namePageUpdate(this)">'+'<select class="custom-select">'+'<option selected>Format ...</option>'+'<option value="1">Editeur de texte/médias</option>'+'<option value="2">Video</option>'+'<option value="3">PDF</option>'+'</select>'+'<div class="ml-1">'+'<button class="btn btn-warning btn-configure" data-hover="Modifier" type="button" onclick="configPage(this)" >Configurer</button>'+'</div>'+'<div class="ml-1">'+'<button class="btn btn-outline-success disabled handle">↕</button>'+'</div>'+'<div class="ml-1">'+'<button class="btn btn-outline-danger btn-delete" onclick="rmThisPage(this)">X</button>'+'</div>'+'</li>';pcontainer.appendChild(newPage);pagesState.push(0);sortablePageUpdate()}
function rmPage(){if(nbPages>0){nbPages--;pcontainer.removeChild(pcontainer.lastChild);pagesState.pop();myConfig.pages.pop()}}
function rmThisPage(e){var elt=e.parentElement.parentElement;var pageNum=e.parentElement.parentElement.id.substring(4);console.log(myConfig);elt.parentNode.removeChild(elt);pagesState.splice(pageNum-1,1);myConfig.pages.splice(pageNum-1,1);nbPages--;console.log(myConfig);for(var i=pageNum;i<=pcontainer.children.length;i++){console.log(pcontainer.children[i-1].id+" -> "+i);pcontainer.children[i-1].id="page"+i;pcontainer.children[i-1].getElementsByClassName("input-group-text")[0].innerHTML="#"+(i)}}
var itemsBeforeUpdate="";var items="";function sortablePageUpdate(){sortable('.js-sortable',{forcePlaceholderSize:!0,handle:'.handle',});sortable('.sortable')[0].addEventListener('sortupdate',function(e){if(!(itemsBeforeUpdate===e.detail.origin.itemsBeforeUpdate&&items===e.detail.origin.items)){itemsBeforeUpdate=e.detail.origin.itemsBeforeUpdate;items=e.detail.origin.items
var i=0;var mem_myConfig=JSON.parse(JSON.stringify(myConfig));var mem_pagesState=pagesState.slice(0)
for(const pageElt of pcontainer.children){var newPageNum=i;var oldPageNum=(pageElt.id.substring(4)-1);if(!(pageElt.id.substring(4)==(i+1))){pageElt.id="page"+(i+1);pageElt.getElementsByClassName("input-group-text")[0].innerHTML="#"+(i+1);myConfig.pages[newPageNum]=mem_myConfig.pages[oldPageNum];pagesState[newPageNum]=mem_pagesState[oldPageNum]}
i++}}})}
var currentPage,currentPageName,currentPageNumber;var childNodes;var format;function configPage(e){currentPage=e.parentElement.parentElement;currentPageNumber=currentPage.id.substring(4);childNodes=currentPage.childNodes;format=childNodes[2].options[childNodes[2].selectedIndex].value;currentPageName=childNodes[1].value;switch(format){case "1":configTextEditor();maintitle.innerHTML="TEXTE - Page "+currentPageNumber;break;case "2":maintitle.innerHTML="VIDEO - Page "+currentPageNumber;configVideo();checkVideoOptions();break;case "3":configPdf();checkPdfOptions()
maintitle.innerHTML="PDF - Page "+currentPageNumber;break;default:currentPage.getElementsByClassName("custom-select")[0].className="custom-select border-warning";break}}
function updatePagesState(newState){var pageInput=document.getElementById("page"+currentPageNumber);pagesState[currentPageNumber-1]=newState;var concernedButton=pageInput.getElementsByClassName("btn-configure")[0];document.getElementById("page"+currentPageNumber).getElementsByClassName("custom-select")[0].className="custom-select border-success";concernedButton.className="btn btn-success btn-configure hover-btn";concernedButton.innerHTML="<span>Configuré</span>"}
function namePageUpdate(inputElt){var pageNumber=inputElt.parentElement.id.substring(4);if(document.getElementById("page"+pageNumber).getElementsByClassName("btn btn-success")[0]){myConfig.pages[pageNumber-1].pageName=inputElt.value}}
function checkOptions(){if(switch1.checked){switch3.disabled=!1}else{switch3.checked=!1;switch3.disabled=!0}}
function configVideo(){hideByClass("configurator");chapcontainer.innerHTML="";nbOfChapters=0;if(pagesState[currentPageNumber-1]===2){var chaps=myConfig.pages[currentPageNumber-1].chapters;for(var i=0;i<chaps.length;i++){createChapterInput();document.getElementById("input-title-"+nbOfChapters).value=chaps[nbOfChapters-1].name;document.getElementById("input-date-"+nbOfChapters).value=chaps[nbOfChapters-1].date}
var index=1;for(const option of myConfig.pages[currentPageNumber-1].options){document.getElementById("customCheck"+index).checked=option;index++}
fileType=myConfig.pages[currentPageNumber-1].videoType;fileName=myConfig.pages[currentPageNumber-1].videoName;document.getElementById("input-file-name").innerHTML=fileName;myPlayer.src({type:fileType,src:myURLs.get(fileName)});myPlayer.pause()}else{var index=0;document.getElementById("input-file-name").innerHTML="Choisir un fichier video";for(const option of document.getElementsByClassName("custom-control-input video-option")){option.checked=!1;index++}}
showByClass("configurator-video")}
function saveVideo(){if(saveVideoConfig()==!0){hideByClass("configurator");maintitle.innerHTML="LOUSTIC OS - Créer";showByClass("configurator-main")}}
function exitVideo(){hideByClass("configurator");maintitle.innerHTML="LOUSTIC OS - Créer";showByClass("configurator-main");myPlayer.reset();videoerror.innerHTML="";inputGroupVideo.value="";document.getElementById("input-file-name").innerHTML="Choisir un fichier video"}
quill.setHTML=(html)=>{editor.innerHTML=html};quill.getHTML=()=>{return editor.innerHTML};function configTextEditor(){hideByClass("configurator");let state=pagesState[currentPageNumber-1];if(state===1){quill.setContents(myConfig.pages[currentPageNumber-1].text)}else{quill.setText('')}
showByClass("configurator-text-editor")}
function saveText(){if(saveTextConfig()==!0){hideByClass("configurator");maintitle.innerHTML="LOUSTIC OS - Créer";showByClass("configurator-main")}}
function exitText(){hideByClass("configurator");maintitle.innerHTML="LOUSTIC OS - Créer";showByClass("configurator-main")}
function configPdf(){hideByClass("configurator");resetPdf();inputGroupPdf.value="";chappdfcontainer.innerHTML=""
pdferror.innerHTML="";pager.style.display="none";nbPdfChapters=0;for(const option of document.getElementsByClassName("pdf-option")){option.checked=!1}
let state=pagesState[currentPageNumber-1];if(state===3){pager.style.display="block";pdfName=myConfig.pages[currentPageNumber-1].pdf;initPDFViewer(myURLs.get(pdfName));document.getElementById("input-pdf-name").innerHTML=pdfName;for(const chap of myConfig.pages[currentPageNumber-1].chapters){createPdfChapter()
chappdfcontainer.lastChild.getElementsByClassName("pdfchapter-title")[0].value=chap.name;chappdfcontainer.lastChild.getElementsByClassName("pdfchapter-slide")[0].value=chap.date}
var i=0;for(const option of myConfig.pages[currentPageNumber-1].options){document.getElementsByClassName("pdf-option")[i].checked=option;i++}}
showByClass("configurator-pdf")}
function savePdf(){if(savePdfConfig()==!0){hideByClass("configurator");maintitle.innerHTML="LOUSTIC OS - Créer";showByClass("configurator-main")}}
function exitPdf(){hideByClass("configurator");maintitle.innerHTML="LOUSTIC OS - Créer";showByClass("configurator-main")}
var importedFiles=new Map();var loadedConfig="";$(document).on('click','.load',function(){var file=$(this).parent().parent().parent().find('.loadfile');file.trigger('click')});function loadFiles(files){for(const file of files){if(file.type==="application/json"){if(loadedConfig!=""){alert("Le fichier : "+file.name+" n'a pas été importé, veuillez ne sélectionner qu'un fichier de configuration (.json)")}else{imported.innerHTML+='<li class="list-group-item list-group-item-primary my-1">'+file.name+'</li>';var selectedFile=file;var reader=new FileReader();reader.onload=function(){loadedConfig=JSON.parse(reader.result)};reader.readAsText(selectedFile);reader.onloadend=function(){controlConfig(!1)};document.getElementById("load-file-name").innerHTML="Importer les fichiers annexes requis";input.accept="video/*, application/pdf";input.multiple=!0}}else{imported.innerHTML+='<li class="list-group-item my-1">'+file.name+'</li>';importedFiles.set(file.name,file);controlConfig(!1)}}}
function controlConfig(canBeLoaded){var isCorrect=!0;var missingFiles=new Set([]);var errorMessages="";mainerror.innerHTML="";$('[data-toggle="popover"]').popover("hide");if(loadedConfig!==""){var imp=new Set([]);for(const impFile of importedFiles.values()){imp.add(impFile.name)}
for(const page of loadedConfig.pages){if(page.type==="video"){if(!imp.has(page.videoName)){missingFiles.add("Veuillez ajouter le fichier manquant : "+page.videoName);isCorrect=!1}}
if(page.type==="pdf"){if(!imp.has(page.pdf)){missingFiles.add("Veuillez ajouter le fichier manquant : "+page.pdf);isCorrect=!1}}}}else{errorMessages="Veuillez sélectionner un fichier de configuration .json";isCorrect=!1}
if(isCorrect){btnSelectConfig.style.display="inline";document.getElementById("load-file-name").className="load btn btn-outline-success";document.getElementById("load-file-name").disabled=!0;document.getElementById("importload-btn").className="load btn btn-outline-success";document.getElementById("importload-btn").disabled=!0;if(canBeLoaded){loadConfig()}}else{for(const message of missingFiles){mainerror.innerHTML+=missingAlert(message)}
if(errorMessages!=""){mainerror.innerHTML+=bAlert(errorMessages)}}}
function loadConfig(){pcontainer.innerHTML="";myURLs=new Map();pagesState=[];myConfig=loadedConfig;nbPages=0;for(let i=1;i<=myConfig.options.length;i++){document.getElementById("switch"+i).checked=myConfig.options[i-1]}
checkOptions();let index=0;document.getElementById("config-name").value=myConfig.name;for(const page of myConfig.pages){currentPageNumber=index+1;addPage();document.getElementById("page"+currentPageNumber).getElementsByClassName("form-control")[0].value=page.pageName;if(page.type==="video"){updatePagesState(2);document.getElementById("page"+currentPageNumber).getElementsByClassName("custom-select")[0].selectedIndex=2;fileUrl=URL.createObjectURL(importedFiles.get(page.videoName));myURLs.set(page.videoName,fileUrl)}else if(page.type==="text"){updatePagesState(1);document.getElementById("page"+currentPageNumber).getElementsByClassName("custom-select")[0].selectedIndex=1}else if(page.type==="pdf"){updatePagesState(3);document.getElementById("page"+currentPageNumber).getElementsByClassName("custom-select")[0].selectedIndex=3;fileUrl=URL.createObjectURL(importedFiles.get(page.pdf));myURLs.set(page.pdf,fileUrl)}
index++}
emptyLoad()}
function emptyLoad(){mainerror.innerHTML="";imported.innerHTML="";importedFiles=new Map();loadedConfig="";document.getElementById("load-file-name").className="load btn btn-outline-primary";document.getElementById("load-file-name").disabled=!1;document.getElementById("importload-btn").className="load btn btn-primary";document.getElementById("importload-btn").disabled=!1;btnSelectConfig.style.display="none";document.getElementById("load-file-name").innerHTML="Charger un fichier de configuration (.json)";input.accept="application/json";input.multiple=!1;input.value=""}
var nbOfChapters=0;var fileUrl;var fileType;var fileName;$(document).on('click','.browse',function(){var file=$(this).parent().parent().parent().find('.file');file.trigger('click')});function handleFiles(file){if(isSomething(file[0])){document.getElementById("input-file-name").innerHTML=file[0].name;fileUrl=URL.createObjectURL(file[0]);myURLs.set(file[0].name,fileUrl);fileType=file[0].type;fileName=file[0].name;myPlayer.src({type:fileType,src:fileUrl});myPlayer.pause();myPlayer.load()}}
function createChapterInput(){nbOfChapters++;var div1=document.createElement("div");div1.className="input-group my-1";div1.id="chapter"+nbOfChapters;div1.innerHTML='<div class="input-group-prepend">'+'<span class="input-group-text">Chapitre '+nbOfChapters+'</span>'+'</div>'+'<input type="text" class="form-control chapter-title" id="input-title-'+nbOfChapters+'" placeholder="Titre" required pattern="^[A-Za-zÀ-ÖØ-öø-ÿ0-9_.,!:-? ]*$">'+'<input type="text" class="form-control chapter-date" id="input-date-'+nbOfChapters+'" placeholder="(HH:)MM:SS" required pattern="((0?[0-9]|1[0-9]):)?([0-5]?[0-9]:)([0-5][0-9])">';chapcontainer.appendChild(div1);checkVideoOptions()}
function removeChapterInput(){if(nbOfChapters>0){chapcontainer.removeChild(chapcontainer.lastChild);nbOfChapters--}
checkVideoOptions()}
function checkVideoOptions(){if(customCheck3.checked&&nbOfChapters!=0){customCheck4.disabled=!1}else{customCheck4.checked=!1;customCheck4.disabled=!0}
if(customCheck4.checked){customCheck5.disabled=!1}else{customCheck5.checked=!1;customCheck5.disabled=!0}
if(customCheck4.checked){customCheck6.disabled=!1}else{customCheck6.checked=!1;customCheck6.disabled=!0}
if(nbOfChapters!=0){customCheck7.disabled=!1}else{customCheck7.checked=!1;customCheck7.disabled=!0}}
let currentPageIndex=0;let pageMode=1;let cursorIndex=Math.floor(currentPageIndex/pageMode);let pdfInstance=null;let totalPagesCount=0;var pdfName="";var nbPdfChapters=0;const viewport=document.querySelector("#viewport");window.initPDFViewer=function(pdfURL){pdfjsLib.getDocument(pdfURL).then(pdf=>{pdfInstance=pdf;totalPagesCount=pdf.numPages;initPager();render()})};function onPagerButtonsClick(event){const action=event.target.getAttribute("data-pager");if(action==="prev"){if(currentPageIndex===0){return}
currentPageIndex-=pageMode;if(currentPageIndex<0){currentPageIndex=0}
render()}
if(action==="next"){if(currentPageIndex===totalPagesCount-1){return}
currentPageIndex+=pageMode;if(currentPageIndex>totalPagesCount-1){currentPageIndex=totalPagesCount-1}
render()}
pagecounter.innerHTML=currentPageIndex+1+"/"+totalPagesCount}
function initPager(){pagecounter.innerHTML="1/"+totalPagesCount;const pager=document.querySelector("#pager");pager.addEventListener("click",onPagerButtonsClick);return()=>{pager.removeEventListener("click",onPagerButtonsClick)}}
function render(){cursorIndex=Math.floor(currentPageIndex/pageMode);const startPageIndex=cursorIndex*pageMode;const endPageIndex=startPageIndex+pageMode<totalPagesCount?startPageIndex+pageMode-1:totalPagesCount-1;const renderPagesPromises=[];for(let i=startPageIndex;i<=endPageIndex;i++){renderPagesPromises.push(pdfInstance.getPage(i+1))}
Promise.all(renderPagesPromises).then(pages=>{const pagesHTML=`<div style="width: ${
		  pageMode > 1 ? "50%" : "100%"
		}"><canvas></canvas></div>`.repeat(pages.length);viewport.innerHTML=pagesHTML;pages.forEach(renderPage)})}
function renderPage(page){let pdfViewport=page.getViewport(1);const container=viewport.children[page.pageIndex-cursorIndex*pageMode];pdfViewport=page.getViewport(container.offsetWidth/pdfViewport.width);const canvas=container.children[0];const context=canvas.getContext("2d");canvas.height=pdfViewport.height;canvas.width=pdfViewport.width;page.render({canvasContext:context,viewport:pdfViewport})}
function resetPdf(){currentPageIndex=0;cursorIndex=Math.floor(currentPageIndex/pageMode);pdfInstance=null;totalPagesCount=0;viewport.innerHTML="";document.getElementById("input-pdf-name").innerHTML="Choisir un fichier pdf"}
function handlePdf(file){if(isSomething(file[0])){resetPdf();fileUrl=URL.createObjectURL(file[0]);pdfName=file[0].name
document.getElementById("input-pdf-name").innerHTML=pdfName;pager.style.display="block";myURLs.set(file[0].name,fileUrl);initPDFViewer(fileUrl)}}
function createPdfChapter(){nbPdfChapters++;var div1=document.createElement("div");div1.className="input-group my-1";div1.id="chapter"+nbPdfChapters;div1.innerHTML='<div class="input-group-prepend">'+'<span class="input-group-text">Chapitre '+nbPdfChapters+'</span>'+'</div>'+'<input type="text" class="form-control pdfchapter-title" id="pdfinput-title-'+nbPdfChapters+'" placeholder="Titre" required pattern="^[A-Za-zÀ-ÖØ-öø-ÿ0-9_.,!:-? ]*$">'+'<input type="number" min="0" class="form-control pdfchapter-slide" id="pdfinput-slide-'+nbPdfChapters+'" placeholder="N° page" required >';chappdfcontainer.appendChild(div1);checkPdfOptions()}
function removePdfChapter(){if(nbPdfChapters>0){chappdfcontainer.removeChild(chappdfcontainer.lastChild);nbPdfChapters--;checkPdfOptions()}}
function checkPdfOptions(){if(pdfOption1.checked&&nbPdfChapters!=0){pdfOption2.disabled=!1}else{pdfOption2.checked=!1;pdfOption2.disabled=!0}
if(pdfOption2.checked){pdfOption3.disabled=!1}else{pdfOption3.checked=!1;pdfOption3.disabled=!0}}
class maConfig{constructor(name,options,pages){this.name=name;this.options=options;this.pages=pages}}
class ConfigVideoJson{constructor(videoName,videoType,options,chapters){this.pageName=currentPageName;this.pageNumber=currentPageNumber;this.type="video";this.videoName=videoName;this.videoType=videoType;this.options=options;this.chapters=chapters}}
class ChapJson{constructor(name,date){this.name=name;this.date=date}}
class ConfigTextJson{constructor(text){this.pageName=currentPageName;this.pageNumber=currentPageNumber;this.type="text";this.text=text}}
class ConfigPdfJson{constructor(pdfName,options,chapters){this.pageName=currentPageName;this.pageNumber=currentPageNumber;this.type="pdf";this.pdf=pdfName;this.options=options;this.chapters=chapters}}
var myConfig=new maConfig("",[],[]);function saveVideoConfig(){var chapterTitleElts=document.getElementsByClassName("chapter-title");var chapterDateElts=document.getElementsByClassName("chapter-date");var videoOptionsElts=document.getElementsByClassName("video-option");var chapters=[];var options=[];var index=0;var complete=!0;var errorMessages=new Set([]);videoerror.innerHTML="";for(var eltTitle of chapterTitleElts){var newChap=new ChapJson(eltTitle.value,"-1");if(!eltTitle.checkValidity()){complete=!1;errorMessages.add("Un titre ne respecte pas le format autorisé");eltTitle.className="form-control chapter-title border-danger"}else{eltTitle.className="form-control chapter-title border-success"}
chapters.push(newChap)}
var prevDate=-1;for(var eltDate of chapterDateElts){chapters[index].date=eltDate.value;if(!eltDate.checkValidity()){complete=!1;errorMessages.add("Au moins un timer ne respecte pas le format (HH:)MM:SS (Heure facultative)");eltDate.className="form-control chapter-date border-danger"}else{if(prevDate<toSeconds(eltDate.value)){eltDate.className="form-control chapter-date border-success"}else{complete=!1;errorMessages.add("Les timers doivent être dans un ordre croissant et compris dans le temps de la video");eltDate.className="form-control chapter-date border-danger"}
prevDate=toSeconds(eltDate.value)}
if(eltDate&&myPlayer.duration()<toSeconds(eltDate.value)){complete=!1;eltDate.className="form-control chapter-date border-danger";errorMessages.add("Les timers doivent être dans un ordre croissant et compris dans le temps de la video")}
index++}
for(const videoOptionElt of videoOptionsElts){options.push(videoOptionElt.checked)}
if(!isSomething(fileName)||!isSomething(myPlayer.src())){complete=!1;errorMessages.add("Veuillez importer un fichier video")}
if(complete){let newVideoConfig=new ConfigVideoJson(fileName,fileType,options,chapters);myConfig.pages[currentPageNumber-1]=newVideoConfig;updatePagesState(2);myPlayer.reset();videoerror.innerHTML="";inputGroupVideo.value="";return!0}else{for(const message of errorMessages){videoerror.innerHTML+=bAlert(message)}
return!1}}
function saveTextConfig(){var cont=quill.getContents();let newTextConfig=new ConfigTextJson(cont);myConfig.pages[currentPageNumber-1]=newTextConfig;updatePagesState(1);return!0}
function savePdfConfig(){var chapters=[];var options=[];var errorMessages=new Set([]);pdferror.innerHTML="";if(pdfInstance===null){errorMessages.add(bAlert("Ajouter un pdf"))}
else{var prevSlide=-1;var index=0;for(const chap of chappdfcontainer.children){var titleElt=chap.getElementsByClassName("pdfchapter-title")[0];var slideElt=chap.getElementsByClassName("pdfchapter-slide")[0];chapters[index]=new ChapJson(titleElt.value,slideElt.value);if(titleElt.checkValidity()){titleElt.classList.add("border-success");titleElt.classList.remove("border-danger")}else{errorMessages.add(bAlert("Titre invalide"));titleElt.classList.remove("border-success");titleElt.classList.add("border-danger")}
if(slideElt.checkValidity()){slideElt.classList.add("border-success");slideElt.classList.remove("border-danger");if((prevSlide>=+slideElt.value)||(+slideElt.value>totalPagesCount)){errorMessages.add(bAlert("Chap pas dans l'ordre, pas compris dans le nb de page, mauvais format"));slideElt.classList.remove("border-success");slideElt.classList.add("border-danger")}
if(slideElt.value){prevSlide=slideElt.value}}else{errorMessages.add(bAlert("Chap pas dans l'ordre, pas compris dans le nb de page, mauvais format"));slideElt.classList.remove("border-success");slideElt.classList.add("border-danger")}
index++}}
for(const mess of errorMessages){pdferror.innerHTML+=mess}
if(pdferror.innerHTML===""){for(const optionElt of document.getElementsByClassName("pdf-option")){options.push(optionElt.checked)}
let newPdfConfig=new ConfigPdfJson(pdfName,options,chapters);myConfig.pages[currentPageNumber-1]=newPdfConfig;updatePagesState(3);inputGroupPdf.value="";return!0}
return!1}
function finishConfig(){var options=[];mainerror.innerHTML="";var errorMessages=new Set([]);for(const optionElt of document.getElementsByClassName("config-option")){options.push(optionElt.checked)}
myConfig.name=document.getElementById("config-name").value;myConfig.options=options;if(configChecker()==!0){console.log(JSON.stringify(myConfig));var dataStr="data:text/json;charset=utf-8,"+encodeURIComponent(JSON.stringify(myConfig));var dlAnchorElem=document.getElementById('download-config');dlAnchorElem.setAttribute("href",dataStr);dlAnchorElem.setAttribute("download",myConfig.name+".json");dlAnchorElem.click()}else{for(const message of errorMessages){mainerror.innerHTML+=bAlert(message)}}
function configChecker(){if(!pagesState.every(isSet)){errorMessages.add("Au moins une page n'a pas été configurée")}
if(!pagesState.length>0){errorMessages.add("Veuillez ajouter au moins une page")}
if(!isSomething(myConfig.name)){errorMessages.add("Veuillez ajouter un nom à votre configuration");document.getElementById("config-name").className="form-control border-danger"}else{document.getElementById("config-name").className="form-control border-success"}
return pagesState.every(isSet)&&pagesState.length>0&&isSomething(myConfig.name)}}
function hideByClass(className){for(eltsToHide of document.getElementsByClassName(className)){eltsToHide.style.display='none'}}
function showByClass(className){for(eltsToHide of document.getElementsByClassName(className)){eltsToHide.style.display='block';eltsToHide.classList.add("fadein")}}
function isSet(pageState){return pageState>0}
function isSomething(params){if(params===""||params===null||params===undefined){return!1}
return!0}
function bAlert(message){return'<div class="alert alert-warning alert-dismissible" role="alert">'+'<strong>Erreur</strong> '+message+'<button type="button" class="close" data-dismiss="alert" aria-label="Close">'+'<span aria-hidden="true">&times;'+'</span></button></div>'}
function missingAlert(message){return'<div class="alert alert-info alert-dismissible" role="alert">'+'<strong>Fichier requis</strong> '+message+'<button type="button" class="close" data-dismiss="alert" aria-label="Close">'+'<span aria-hidden="true">&times;'+'</span></button></div>'}
function toSeconds(time){var a=time.split(':');var seconds=0;switch(a.length){case 1:seconds=time
break;case 2:seconds=(+a[0])*60+(+a[1]);break;case 3:seconds=(+a[0])*3600+(+a[1])*60+(+a[2]);break;default:alert("Heure du chapitre dans un format incorrect")
break}
return seconds}