var myPlayer=videojs('myvideo');var nextChapButton=myPlayer.controlBar.addChild("button",{},1);var nextChapButtonDom=nextChapButton.el();nextChapButtonDom.innerHTML="<b>>></b>";nextChapButtonDom.onclick=function(){nextChap()}
var prevChapButton=myPlayer.controlBar.addChild("button",{},0);var prevChapButtonDom=prevChapButton.el();prevChapButtonDom.innerHTML="<b><<</b>";prevChapButtonDom.onclick=function(){prevChap()}
var myConfig="";var importedFiles=new Map();var currentChapters=new Map();var testID="";var myCsvGeneral="";var myCsvLogs="";var currentPageNumber=0;var currentChapterNumber=0;var startTimeOnTest=0;var startTimeOnPage=0;var previousTime=0;var myReachedPage=0;var quill=new Quill('#editor',{modules:{imageResize:!1,toolbar:!1},theme:'snow'});quill.disable()
$(function(){$('[data-toggle="popover"]').popover()})
$(document).on('DOMSubtreeModified',function(){$(function(){$('.fadein').removeClass('fadein')})});$(document).on('click','.browse',function(){var file=$(this).parent().parent().parent().find('.file');file.trigger('click')});function loadFiles(files){for(const file of files){if(file.type==="application/json"){if(myConfig!=""){alert("Le fichier : "+file.name+" n'a pas été importé, veuillez ne sélectionner qu'un fichier de configuration (.json)")}else{imported.innerHTML+='<li class="list-group-item list-group-item-primary my-1">'+file.name+'</li>';var selectedFile=file;var reader=new FileReader();reader.onload=function(){myConfig=JSON.parse(reader.result)};reader.readAsText(selectedFile);reader.onloadend=function(){controlConfig(!1)};document.getElementById("input-file-name").innerHTML="Importer les fichiers annexes requis";input.accept="video/*, application/pdf";input.multiple=!0}}else{imported.innerHTML+='<li class="list-group-item my-1">'+file.name+'</li>';importedFiles.set(file.name,file);controlConfig(!1)}}}
function controlConfig(continueToInfos){var isCorrect=!0;var missingFiles=new Set([]);var errorMessages="";mainerror.innerHTML="";$('[data-toggle="popover"]').popover("hide");if(myConfig!==""){var imp=[];for(const impFile of importedFiles.values()){imp.push(impFile.name)}
for(const page of myConfig.pages){if(page.type==="video"){if(!imp.includes(page.videoName)){missingFiles.add("Veuillez ajouter le fichier manquant : "+page.videoName);isCorrect=!1}}
if(page.type==="pdf"){if(!imp.includes(page.pdf)){missingFiles.add("Veuillez ajouter le fichier manquant : "+page.pdf);isCorrect=!1}}}}else{errorMessages="Veuillez sélectionner un fichier de configuration .json";isCorrect=!1}
if(isCorrect){btnSelectConfig.style.display="inline";document.getElementById("input-file-name").className="browse btn btn-outline-success";document.getElementById("input-file-name").disabled=!0;document.getElementById("import-btn").className="browse btn btn-outline-success";document.getElementById("import-btn").disabled=!0;if(continueToInfos){window.onbeforeunload=function(){return""};personnalInfos()}}else{for(const message of missingFiles){mainerror.innerHTML+=missingAlert(message)}
if(errorMessages!=""){mainerror.innerHTML+=bAlert(errorMessages)}}}
function personnalInfos(){hideByClass("load");hideByClass("navbar");showByClass("load-form-infos");for(const input of document.getElementsByClassName("infos-perso")){input.className="form-control infos-perso";input.value=""}
pagesNameIndex.innerHTML="";myCsvGeneral="";myCsvLogs="";currentPageNumber=0;currentChapterNumber=0;startTimeOnTest=0;startTimeOnPage=0;previousTime=0;myReachedPage=0;tPlay=0;tPlayCSV=0;tChapCSV=0;tPause=0;tChap=0;chapFrom=0;chapTo=0;testID=generateUniqueID();ident.value=testID}
function startConfig(){var correct=!0;for(const input of document.getElementsByClassName("infos-perso")){if(!input.checkValidity()){input.className="form-control infos-perso border-danger";correct=!1}else{input.className="form-control infos-perso border-success"}}
if(correct){hideByClass("load");if(myConfig.options[0]){if(myConfig.options[1]){pagesNameIndex.innerHTML+='<li class="page-item" id="btnPrevPage"><a class="page-link" onclick="prevPage()">Précédent</a></li>'}else{pagesNameIndex.innerHTML+='<li class="page-item" id="btnPrevPage" style="display : none"><a class="page-link" onclick="prevPage()">&laquo;</a></li>'}
for(const page of myConfig.pages){var name=(page.pageNumber)
if(myConfig.options[2]&&page.pageName!=""){name=page.pageName}
pagesNameIndex.innerHTML+='<li class="page-item"><a class="page-link" onclick="jumpToPage('+(page.pageNumber-1)+')">'+name+'&#8203</a></li>'}}
pagesNameIndex.innerHTML+='<li class="page-item active-custom" id="btnNextPage"><a class="page-link" onclick="nextPage()">Suivant</a></li>'
showByClass("pages-index");myCsvLogs=new CsvLogs();myJSONGeneral=new InfosGeneralJSON();for(const page of myConfig.pages){infosDiapo=new InfosDiapo();if(page.type==="video"){for(const chapter of page.chapters){infosDiapo.infosChaps.push(new InfosChap())}}
myJSONGeneral.diapos.push(infosDiapo);myJSONGeneral.sommaire.clicsOn.push(0);myJSONGeneral.nth.push(0)}
startTimeOnTest=Date.now();loadPage()}}
function loadPage(){if(myConfig.options[0]){if(currentPageNumber<1){btnPrevPage.className="page-item disabled-custom"}else{btnPrevPage.className="page-item active-custom"}}
pauseVideo(!1);if(myConfig.pages.length===currentPageNumber){finishConfig()}else{if(myConfig.options[0]){var i=0;for(pageNameIndex of pagesNameIndex.getElementsByTagName("li")){if(currentPageNumber+1===i){pageNameIndex.classList.add("active")}else if(i!=0&&i!=myConfig.pages.length+1){pageNameIndex.classList.remove("active")}
i++}}
var currentPage=myConfig.pages[currentPageNumber];startTimeOnPage=Date.now();currentChapterNumber=0;myCsvLogs.addLine("START_PAGE");switch(currentPage.type){case "video":loadVideo();break;case "text":loadText();break;case "pdf":loadPdf();break;default:break}}}
function nextPage(){myCsvLogs.addLine("NEXT_PAGE");currentPageNumber++;loadPage()}
function prevPage(){myCsvLogs.addLine("PREV_PAGE");currentPageNumber--;loadPage()}
function jumpToPage(pageNumber){myReachedPage=pageNumber;myCsvLogs.addLine("SOMMAIRE");console.log("SOMMAIRE : "+currentPageNumber+"-->"+pageNumber);currentPageNumber=pageNumber;loadPage()}
function finishConfig(){hideByClass("load");hideByClass("pages-index")
showByClass("load-finish");myCsvLogs.addLine("END");console.log(myCsvLogs.toString());console.log(myJSONGeneral);dlcsv()}
function dlcsv(){var dlAnchorElem=document.getElementById('download-link');dlAnchorElem.setAttribute("href",myJSONGeneral.toCSV());dlAnchorElem.setAttribute("download",testID+"_"+document.getElementsByClassName("infos-perso")[0].value+"_syn"+".csv");dlAnchorElem.click()
dlAnchorElem.setAttribute("href",myCsvLogs);dlAnchorElem.setAttribute("download",testID+"_"+document.getElementsByClassName("infos-perso")[0].value+"_logs"+".csv");dlAnchorElem.click()}
function loadVideo(){hideByClass("load");var currentPage=myConfig.pages[currentPageNumber];var currentFile=importedFiles.get(currentPage.videoName);const PPLLOWED=currentPage.options[0];const FREENAV=currentPage.options[1];const VISIBLECHAPZONE=currentPage.options[2];const VISIBLECHAP=currentPage.options[3];const VISIBLEDATECHAP=currentPage.options[4];const CLICKABLECHAP=currentPage.options[5];const NAVIGABLECHAP=currentPage.options[6];myPlayer.one('playing',function(){myCsvLogs.addLine("VIDEO_START")});myPlayer.on('timeupdate',function(){checkChap();if(myConfig.pages[currentPageNumber].type=="video"&&VISIBLECHAP){chapTimerUpdate()}});currentChapters=new Map();var index=0;for(const chapter of myConfig.pages[currentPageNumber].chapters){currentChapters.set(toSeconds(chapter.date),index);index++}
myPlayer.src({type:currentFile.type,src:URL.createObjectURL(currentFile)})
myPlayer.tech_.off('dblclick');myPlayer.controlBar.removeChild('FullscreenToggle');myPlayer.controlBar.removeChild('VolumePanel');if(PPLLOWED){document.querySelector(".vjs-tech").style.pointerEvents="auto";document.querySelector(".vjs-play-control.vjs-control.vjs-button").style.display="block";autoPlay=!1;pauseVideo(!1)}else{document.querySelector(".vjs-tech").style.pointerEvents="none";document.querySelector(".vjs-play-control.vjs-control.vjs-button").style.display="none";autoPlay=!0;playVideo(!1)}
myPlayer.controlBar.progressControl.on('mousedown',function(event){myCsvLogs.addLine("NAVBAR_USED")});myPlayer.controlBar.progressControl.seekBar.on('mousedown',function(event){myCsvLogs.addLine("NAVBAR_USED")});if(FREENAV){document.querySelector(".vjs-progress-control").style.pointerEvents="auto"}else{document.querySelector(".vjs-progress-control").style.pointerEvents="none"}
chapcontainer.innerHTML="";if(VISIBLECHAPZONE){chapcontainer.style.display="block"}else{chapcontainer.style.display="none"}
if(VISIBLECHAP){chapcontainer.innerHTML+='<li class="list-group-item border-0 bg-transparent my-1">Chapitres : </li>';if(VISIBLEDATECHAP){for(const chapter of myConfig.pages[currentPageNumber].chapters){chapcontainer.innerHTML+='<li class="list-group-item bg-transparent my-1 p-0">'+'<button class="btn btn-block btn-outline-primary btn-chapter p-0" type="button" onclick="gotoTime(this.children[1].innerHTML)">'+chapter.name+' : '+chapter.date+'<div class="background">&#8203</div>'+'<div style="display : none;">'+chapter.date+'</div>'+'</button>'+'</li>'}}else{for(const chapter of myConfig.pages[currentPageNumber].chapters){chapcontainer.innerHTML+='<li class="list-group-item bg-transparent my-1 p-0">'+'<button class="btn btn-block btn-outline-primary btn-chapter p-0" type="button" onclick="gotoTime(this.children[1].innerHTML)">'+chapter.name+'<div class="background">&#8203</div>'+'<div style="display : none;">'+chapter.date+'</div>'+'</button>'+'</li>'}}}
if(!CLICKABLECHAP){for(const btn of document.getElementsByClassName("btn-chapter")){btn.disabled="true";btn.className="btn btn-block text-primary btn-outline-secondary btn-chapter"}}
if(NAVIGABLECHAP){nextChapButtonDom.style.display="block";prevChapButtonDom.style.display="block"}else{nextChapButtonDom.style.display="none";prevChapButtonDom.style.display="none"}
myPlayer.load();showByClass("load-video")}
function playVideo(withLog){if(withLog){myCsvLogs.addLine("PLAY")}
myPlayer.play()}
function pauseVideo(withLog){if(withLog){myCsvLogs.addLine("PAUSE")}
myPlayer.pause()}
function gotoTime(time){myPlayer.currentTime(toSeconds(time));myCsvLogs.addLine("CHAP_USED")}
function videoEnded(){myCsvLogs.addLine("VIDEO_END")}
var chapFrom=0;var chapTo=0;function checkChap(){previousTime=myPlayer.currentTime();if(myConfig.pages[currentPageNumber].type==="video"){var tmp=0;for(const chapterDate of currentChapters.keys()){if(myPlayer.currentTime()>=chapterDate){tmp=currentChapters.get(chapterDate)+1}}
if(tmp!=currentChapterNumber){chapFrom=currentChapterNumber;chapTo=tmp;if(!myPlayer.seeking()){currentChapterNumber=tmp;myCsvLogs.addLine("CHAP_ATT");console.log("CHAP_ATT : "+chapFrom+"-->"+chapTo)}}}}
function chapTimerUpdate(){if(myConfig.pages[currentPageNumber].options[4]){var i=1;for(const chap of document.getElementsByClassName("background")){if(i===currentChapterNumber){var chapCurrentTime=myPlayer.currentTime()-toSeconds(myConfig.pages[currentPageNumber].chapters[currentChapterNumber-1].date);var chapDuration=1;if(currentChapterNumber==myConfig.pages[currentPageNumber].chapters.length){chapDuration=myPlayer.duration()-toSeconds(myConfig.pages[currentPageNumber].chapters[currentChapterNumber-1].date)}else{chapDuration=toSeconds(myConfig.pages[currentPageNumber].chapters[currentChapterNumber].date)-toSeconds(myConfig.pages[currentPageNumber].chapters[currentChapterNumber-1].date)}
chap.style.width=(100*chapCurrentTime/chapDuration)+'%'}else{chap.style.width="0%"}
i++}}else{var i=1;for(const btnchap of document.getElementsByClassName("btn-chapter")){if(i===currentChapterNumber){btnchap.classList.add("border-danger")}else{btnchap.classList.remove("border-danger")}
i++}}}
function nextChap(){if(currentChapterNumber===myConfig.pages[currentPageNumber].chapters.length){}else{myPlayer.currentTime(toSeconds(myConfig.pages[currentPageNumber].chapters[currentChapterNumber].date));myCsvLogs.addLine("NEXT_CHAP")}}
function prevChap(){if(currentChapterNumber===0){myPlayer.currentTime(0)}else if(currentChapterNumber===1){myPlayer.currentTime(0)}else{myPlayer.currentTime(toSeconds(myConfig.pages[currentPageNumber].chapters[currentChapterNumber-2].date))}
myCsvLogs.addLine("PREV_CHAP")}
function loadText(){hideByClass("load");showByClass("load-text");quill.setContents(myConfig.pages[currentPageNumber].text)}
function loadPdf(){hideByClass("load");resetPdf();pdfchapcontainer.innerHTML="";var currentPage=myConfig.pages[currentPageNumber];var currentFile=importedFiles.get(currentPage.pdf);initPDFViewer(URL.createObjectURL(currentFile));const VISIBLECHAPZONE=currentPage.options[0];const VISIBLECHAP=currentPage.options[1];const CLICKABLECHAP=currentPage.options[2];if(VISIBLECHAPZONE){pdfchapcontainer.style.display="block"}else{pdfchapcontainer.style.display="none"}
if(VISIBLECHAP){if(CLICKABLECHAP){pdfchapcontainer.innerHTML+='<li class="list-group-item border-0 bg-transparent my-1">Chapitres :</li>';for(const chapter of currentPage.chapters){pdfchapcontainer.innerHTML+='<li class="list-group-item bg-transparent my-1 p-0">'+'<button class="btn btn-block btn-outline-primary btn-chapter btn-chap-pdf p-0" type="button" onclick="gotoSlide(this.children[0].innerHTML)">'+chapter.name+' : '+chapter.date+'<div style="display : none;">'+chapter.date+'</div>'+'</button>'+'</li>';}}else{for(const chapter of currentPage.chapters){pdfchapcontainer.innerHTML+='<li class="list-group-item bg-transparent my-1 p-0">'+'<button class="btn btn-block text-primary btn-outline-secondary btn-chapter btn-chap-pdf p-0 disabled" type="button">'+chapter.name+' : '+chapter.date+'<div class="background">&#8203</div>'+'</button>'+'</li>'}}}
showByClass("load-pdf")}
let currentPageIndex=0;let pageMode=1;let cursorIndex=Math.floor(currentPageIndex/pageMode);let pdfInstance=null;let totalPagesCount=0;var pdfName;var fromSlide=0;var chapChecker=[];const viewport=document.querySelector("#viewport");window.initPDFViewer=function(pdfURL){pdfjsLib.getDocument(pdfURL).then(pdf=>{pdfInstance=pdf;totalPagesCount=pdf.numPages;initPager();render()})};function onPagerButtonsClick(event){const action=event.target.getAttribute("data-pager");if(action==="prev"){if(currentPageIndex===0){return}
currentPageIndex-=pageMode;if(currentPageIndex<0){currentPageIndex=0}else{fromSlide=currentPageIndex+1;myCsvLogs.addLine("PREV_SLIDE");render()}}
if(action==="next"){if(currentPageIndex===totalPagesCount-1){return}
currentPageIndex+=pageMode;if(currentPageIndex>totalPagesCount-1){currentPageIndex=totalPagesCount-1}else{fromSlide=currentPageIndex-1;myCsvLogs.addLine("NEXT_SLIDE");render()}}}
function initPager(){chapChecker=[];for(const chap of myConfig.pages[currentPageNumber].chapters){chapChecker.push(chap.date)}
chapChecker.push(Number.MAX_SAFE_INTEGER);const pager=document.querySelector("#pager");pager.addEventListener("click",onPagerButtonsClick);return()=>{pager.removeEventListener("click",onPagerButtonsClick)}}
function render(){cursorIndex=Math.floor(currentPageIndex/pageMode);const startPageIndex=cursorIndex*pageMode;const endPageIndex=startPageIndex+pageMode<totalPagesCount?startPageIndex+pageMode-1:totalPagesCount-1;const renderPagesPromises=[];for(let i=startPageIndex;i<=endPageIndex;i++){renderPagesPromises.push(pdfInstance.getPage(i+1))}
Promise.all(renderPagesPromises).then(pages=>{const pagesHTML=`<div style="width: ${
		  pageMode > 1 ? "50%" : "100%"
		}"><canvas></canvas></div>`.repeat(pages.length);viewport.innerHTML=pagesHTML;pages.forEach(renderPage)});slidecounter.innerHTML=currentPageIndex+1+"/"+totalPagesCount
var i=0;for(const chap of myConfig.pages[currentPageNumber].chapters){var btn=document.getElementsByClassName("btn-chap-pdf")[i];if(chap.date==(currentPageIndex+1)){myCsvLogs.addLine("CHAP_SLIDE_ATT")}
if(currentPageIndex+1>=chapChecker[i]&&currentPageIndex+1<chapChecker[i+1]){btn.classList.add("border-danger")}else{btn.classList.remove("border-danger")}
i++}}
function renderPage(page){let pdfViewport=page.getViewport(1);const container=viewport.children[page.pageIndex-cursorIndex*pageMode];pdfViewport=page.getViewport(container.offsetWidth/pdfViewport.width);const canvas=container.children[0];const context=canvas.getContext("2d");canvas.height=pdfViewport.height;canvas.width=pdfViewport.width;page.render({canvasContext:context,viewport:pdfViewport})}
function resetPdf(){currentPageIndex=0;cursorIndex=Math.floor(currentPageIndex/pageMode);pdfInstance=null;totalPagesCount=0;viewport.innerHTML=""}
function gotoSlide(n){if(currentPageIndex!=(n-1)){fromSlide=currentPageIndex;currentPageIndex=n-1;myCsvLogs.addLine("GOTO_SLIDE");render()}}
class Csv{constructor(){this.lines=[];this.lines.push("data:text/csv;charset=utf-8,")}
toString(){var res="";for(const line of this.lines){res+=line+"\n"}
return res}}
var tPlay=0;var tPlayCSV=0;var tChapCSV=0;var tfChapSlide=0;var tPause=0;var tChap=0;class CsvLogs extends Csv{constructor(){super();this.lines.push("Timer;Current page;Current chap;Reached page;Reched chap;Action;Time from test begining;Time from page begining;Video timer;Time from chap begining;Time from PLAY;Curr slide Chap;Reached slide Chap;Time from chap slide begining")}
addLine(action){var now=Date.now();var d=new Date();var timer=d.toLocaleDateString()+"("+d.toLocaleDateString("fr-FR",{weekday:"short"})+")-"+d.toLocaleTimeString();var cPageNumber=currentPageNumber+1;var cChapterNumber="";var reachedPage="";var reachedChap="";var tfTest=duration(startTimeOnTest,now);var tfPage=duration(startTimeOnPage,now);var videoTimer="";var tfChap="";var tfPlay="";if(currentPageNumber<myConfig.pages.length&&myConfig.pages[currentPageNumber].type==="video"){cChapterNumber=currentChapterNumber+1;videoTimer=myPlayer.currentTime();tfChap=duration(tChapCSV,now);if(tfChap>1500000000){tfChap=""}
tfPlay=duration(tPlayCSV,now);if(tfPlay>1500000000){tfPlay=""}}
var tfChapS=""
if(currentPageNumber<myConfig.pages.length&&myConfig.pages[currentPageNumber].type==="pdf"){tfChapS=duration(tfChapSlide,now);if(tfChapS>1500000000){tfChapS=""}else{tfChapS=toNum(tfChapS)}}
switch(action){case "START_PAGE":tfChapSlide=0;myJSONGeneral.nth[currentPageNumber]++;myJSONGeneral.visites.push(new InfosVisite(tfTest));this.lines.push(timer+";"+cPageNumber+";"+""+";"+""+";"+""+";"+action+";"+toNum(tfTest)+";"+"0"+";"+""+";"+""+";"+""+";"+""+";"+""+";"+"");break;case "CHAP_ATT":tChapCSV=now;reachedChap=chapTo;if(chapFrom>0){if(tPlay!=0){myJSONGeneral.diapos[currentPageNumber].infosChaps[chapFrom-1].dureePlay+=duration(tPlay,now);myJSONGeneral.diapos[currentPageNumber].dureePlay+=duration(tPlay,now);tPlay=now}
if(tPause!=0){myJSONGeneral.diapos[currentPageNumber].infosChaps[chapFrom-1].dureePause+=duration(tPause,now);myJSONGeneral.diapos[currentPageNumber].dureePause+=duration(tPause,now);tPause=now}
if(tChap!=0){myJSONGeneral.diapos[currentPageNumber].infosChaps[chapFrom-1].duree+=duration(tChap,now);tChap=now}}
if(!myPlayer.paused()){tPlay=now}else{tPause=now}
tChap=now;this.lines.push(timer+";"+cPageNumber+";"+cChapterNumber+";"+""+";"+reachedChap+";"+action+";"+toNum(tfTest)+";"+toNum(tfPage)+";"+toNum(videoTimer)+";"+toNum(tfChap)+";"+toNum(tfPlay)+";"+""+";"+""+";"+"");break;case "CHAP_USED":myJSONGeneral.visites[myJSONGeneral.visites.length-1].nbChapList++;this.lines.push(timer+";"+cPageNumber+";"+cChapterNumber+";"+""+";"+""+";"+action+";"+toNum(tfTest)+";"+toNum(tfPage)+";"+toNum(previousTime)+";"+toNum(tfChap)+";"+toNum(tfPlay)+";"+""+";"+""+";"+"");break;case "PREV_CHAP":myJSONGeneral.visites[myJSONGeneral.visites.length-1].nbChapPrec++;this.lines.push(timer+";"+cPageNumber+";"+cChapterNumber+";"+""+";"+""+";"+action+";"+toNum(tfTest)+";"+toNum(tfPage)+";"+toNum(previousTime)+";"+toNum(tfChap)+";"+toNum(tfPlay)+";"+""+";"+""+";"+"");break;case "NEXT_CHAP":myJSONGeneral.visites[myJSONGeneral.visites.length-1].nbChapSuiv++;this.lines.push(timer+";"+cPageNumber+";"+cChapterNumber+";"+""+";"+""+";"+action+";"+toNum(tfTest)+";"+toNum(tfPage)+";"+toNum(previousTime)+";"+toNum(tfChap)+";"+toNum(tfPlay)+";"+""+";"+""+";"+"");break;case "VIDEO_START":this.lines.push(timer+";"+cPageNumber+";"+cChapterNumber+";"+""+";"+""+";"+action+";"+toNum(tfTest)+";"+toNum(tfPage)+";"+toNum(videoTimer)+";"+""+";"+""+";"+""+";"+""+";"+"");break;case "VIDEO_END":tPlay=0;tPause=0;this.lines.push(timer+";"+cPageNumber+";"+""+";"+""+";"+""+";"+action+";"+toNum(tfTest)+";"+toNum(tfPage)+";"+toNum(videoTimer)+";"+toNum(tfChap)+";"+toNum(tfPlay)+";"+""+";"+""+";"+"");break;case "PLAY":tPlayCSV=now;myJSONGeneral.visites[myJSONGeneral.visites.length-1].nbPlay++;if(currentChapterNumber>0){if(tPause!=0){myJSONGeneral.diapos[currentPageNumber].infosChaps[currentChapterNumber-1].dureePause+=duration(tPause,now);myJSONGeneral.diapos[currentPageNumber].dureePause+=duration(tPause,now)}
myJSONGeneral.diapos[currentPageNumber].infosChaps[currentChapterNumber-1].nbPlay++;tPlay=now}
tPause=0;myJSONGeneral.diapos[currentPageNumber].nbPlay++;this.lines.push(timer+";"+cPageNumber+";"+cChapterNumber+";"+""+";"+""+";"+action+";"+toNum(tfTest)+";"+toNum(tfPage)+";"+toNum(videoTimer)+";"+toNum(tfChap)+";"+toNum(tfPlay)+";"+""+";"+""+";"+"");break;case "PAUSE":myJSONGeneral.visites[myJSONGeneral.visites.length-1].nbPause++;console.log(action+" page : "+currentPageNumber+" chap : "+currentChapterNumber)
if(currentChapterNumber>0){if(tPlay!=0){myJSONGeneral.diapos[currentPageNumber].infosChaps[currentChapterNumber-1].dureePlay+=duration(tPlay,now);myJSONGeneral.diapos[currentPageNumber].dureePlay+=duration(tPlay,now)}
myJSONGeneral.diapos[currentPageNumber].infosChaps[currentChapterNumber-1].nbPause++;tPause=now}
tPlay=0;myJSONGeneral.diapos[currentPageNumber].nbPause++;this.lines.push(timer+";"+cPageNumber+";"+cChapterNumber+";"+""+";"+""+";"+action+";"+toNum(tfTest)+";"+toNum(tfPage)+";"+toNum(videoTimer)+";"+toNum(tfChap)+";"+toNum(tfPlay)+";"+""+";"+""+";"+"");break;case "NAVBAR_USED":myJSONGeneral.visites[myJSONGeneral.visites.length-1].nbNavBar++;this.lines.push(timer+";"+cPageNumber+";"+""+";"+""+";"+""+";"+action+";"+toNum(tfTest)+";"+toNum(tfPage)+";"+toNum(previousTime)+";"+toNum(tfChap)+";"+toNum(tfPlay)+";"+""+";"+""+";"+"");break;case "NEXT_PAGE":update_durees();myJSONGeneral.visites[myJSONGeneral.visites.length-1].fin=tfTest;myJSONGeneral.visites[myJSONGeneral.visites.length-1].duree=myJSONGeneral.visites[myJSONGeneral.visites.length-1].fin-myJSONGeneral.visites[myJSONGeneral.visites.length-1].debut;var nexPageNumber=(cPageNumber+1);if(nexPageNumber>myConfig.pages.length){nexPageNumber=""}
this.lines.push(timer+";"+cPageNumber+";"+cChapterNumber+";"+nexPageNumber+";"+""+";"+action+";"+toNum(tfTest)+";"+toNum(tfPage)+";"+toNum(videoTimer)+";"+toNum(tfChap)+";"+toNum(tfPlay)+";"+""+";"+""+";"+tfChapS);break;case "PREV_PAGE":update_durees();myJSONGeneral.visites[myJSONGeneral.visites.length-1].fin=tfTest;myJSONGeneral.visites[myJSONGeneral.visites.length-1].duree=myJSONGeneral.visites[myJSONGeneral.visites.length-1].fin-myJSONGeneral.visites[myJSONGeneral.visites.length-1].debut;this.lines.push(timer+";"+cPageNumber+";"+cChapterNumber+";"+(cPageNumber-1)+";"+""+";"+action+";"+toNum(tfTest)+";"+toNum(tfPage)+";"+toNum(videoTimer)+";"+toNum(tfChap)+";"+toNum(tfPlay)+";"+""+";"+""+";"+tfChapS);break;case "SOMMAIRE":update_durees();myJSONGeneral.visites[myJSONGeneral.visites.length-1].fin=tfTest;myJSONGeneral.visites[myJSONGeneral.visites.length-1].duree=myJSONGeneral.visites[myJSONGeneral.visites.length-1].fin-myJSONGeneral.visites[myJSONGeneral.visites.length-1].debut;myJSONGeneral.sommaire.totalClics++;myJSONGeneral.sommaire.clicsOn[myReachedPage]++;reachedPage=myReachedPage+1;this.lines.push(timer+";"+cPageNumber+";"+cChapterNumber+";"+reachedPage+";"+""+";"+action+";"+toNum(tfTest)+";"+toNum(tfPage)+";"+toNum(videoTimer)+";"+toNum(tfChap)+";"+toNum(tfPlay)+";"+""+";"+""+";"+tfChapS);break;case "END":this.lines.push(timer+";"+""+";"+""+";"+""+";"+""+";"+action+";"+toNum(tfTest)+";"+""+";"+""+";"+""+";"+""+";"+""+";"+""+";"+"");break;case "NEXT_SLIDE":myJSONGeneral.visites[myJSONGeneral.visites.length-1].nbPdfSuiv++;this.lines.push(timer+";"+cPageNumber+";"+""+";"+""+";"+""+";"+action+";"+toNum(tfTest)+";"+toNum(tfPage)+";"+""+";"+""+";"+""+";"+(currentPageIndex)+";"+""+";"+tfChapS);break;case "PREV_SLIDE":myJSONGeneral.visites[myJSONGeneral.visites.length-1].nbPdfPrec++;this.lines.push(timer+";"+cPageNumber+";"+""+";"+""+";"+""+";"+action+";"+toNum(tfTest)+";"+toNum(tfPage)+";"+""+";"+""+";"+""+";"+(currentPageIndex+2)+";"+""+";"+tfChapS);break;case "GOTO_SLIDE":myJSONGeneral.visites[myJSONGeneral.visites.length-1].nbPdfChap++;this.lines.push(timer+";"+cPageNumber+";"+""+";"+""+";"+""+";"+action+";"+toNum(tfTest)+";"+toNum(tfPage)+";"+""+";"+""+";"+""+";"+(fromSlide+1)+";"+""+";"+tfChapS);break;case "CHAP_SLIDE_ATT":this.lines.push(timer+";"+cPageNumber+";"+""+";"+""+";"+""+";"+action+";"+toNum(tfTest)+";"+toNum(tfPage)+";"+""+";"+""+";"+""+";"+(fromSlide+1)+";"+(currentPageIndex+1)+";"+tfChapS);tfChapSlide=now;break;default:console.error("Unknown Action : "+action);break}
function update_durees(){if(currentChapterNumber>0){if(tPlay!=0){myJSONGeneral.diapos[currentPageNumber].infosChaps[currentChapterNumber-1].dureePlay+=duration(tPlay,now);myJSONGeneral.diapos[currentPageNumber].dureePlay+=duration(tPlay,now);tPlay=now}
if(tPause!=0){myJSONGeneral.diapos[currentPageNumber].infosChaps[currentChapterNumber-1].dureePause+=duration(tPause,now);myJSONGeneral.diapos[currentPageNumber].dureePause+=duration(tPause,now);tPause=now}
if(tChap!=0){myJSONGeneral.diapos[currentPageNumber].infosChaps[currentChapterNumber-1].duree+=duration(tChap,now);tChap=now}}
myJSONGeneral.diapos[currentPageNumber].duree+=tfPage}}}
class InfosGeneralJSON{constructor(){this.config=myConfig.name;this.participant="nom_du_participant"+testID;this.diapos=[];this.sommaire=new InfosSommaire;this.visites=[];this.nth=[]}
toCSV(){var res="";var titles="";var values="";var titlesV="";var valuesV="";titles+="Participant;Config"
values+=this.participant+";"+this.config;var iDiapo=1;for(const diapo of this.diapos){var d="D"+iDiapo+"-";titles+=";"+d+"duree"+";"+d+"dureePlay"+";"+d+"dureePause"+";"+d+"nbPlay"+";"+d+"nbPause";values+=";"+toNum(diapo.duree)+";"+toNum(diapo.dureePlay)+";"+toNum(diapo.dureePause)+";"+diapo.nbPlay+";"+diapo.nbPause;var iChap=1;for(const chap of diapo.infosChaps){d="D"+iDiapo+"-C"+iChap+"-";titles+=";"+d+"duree"+";"+d+"dureePlay"+";"+d+"dureePause"+";"+d+"nbPlay"+";"+d+"nbPause";values+=";"+toNum(chap.duree)+";"+toNum(chap.dureePlay)+";"+toNum(chap.dureePause)+";"+chap.nbPlay+";"+chap.nbPause;iChap++}
iDiapo++}
titles+=";Clics sommaire";values+=";"+this.sommaire.totalClics;var iSom=1;for(const clic of this.sommaire.clicsOn){titles+=";Sommaire "+iSom;values+=";"+clic;iSom++}
titlesV+="\n\nDiapo; Nieme visite; Debut; Fin; Duree; Nb vid play; Nb vid pause; Nb vid chap suiv; Nb vid chap prec; Nb vid chap list; Nb vid navbar;Nb pdf prec; Nb pdf suiv; Nb pdf chap list\n";for(const visite of this.visites){valuesV+=(1+visite.diapoNum)+";"+visite.nth+";"+toNum(visite.debut)+";"+toNum(visite.fin)+";"+toNum(visite.duree)+";"+visite.nbPlay+";"+visite.nbPause+";"+visite.nbChapSuiv+";"+visite.nbChapPrec+";"+visite.nbChapList+";"+visite.nbNavBar+";"+visite.nbPdfPrec+";"+visite.nbPdfSuiv+";"+visite.nbPdfChap+"\n"}
res+=titles+"\n"+values+titlesV+valuesV;return"data:text/csv;charset=utf-8,"+res}}
class InfosSommaire{constructor(){this.totalClics=0;this.clicsOn=[]}}
class InfosDiapo{constructor(){this.duree=0;this.dureePlay=0;this.dureePause=0;this.nbPlay=0;this.nbPause=0;this.infosChaps=[]}}
class InfosChap{constructor(){this.duree=0;this.dureePlay=0;this.dureePause=0;this.nbPlay=0;this.nbPause=0}}
class InfosVisite{constructor(debut){this.diapoNum=currentPageNumber;this.nth=myJSONGeneral.nth[currentPageNumber];this.debut=debut;this.fin=0;this.duree=0;this.nbPlay=0;this.nbPause=0;this.nbChapSuiv=0;this.nbChapPrec=0;this.nbChapList=0;this.nbNavBar=0;this.nbPdfPrec=0;this.nbPdfSuiv=0;this.nbPdfChap=0}}
function reloadPage(){window.onbeforeunload=function(){};document.location.reload(!0)}
function hideByClass(className){for(eltsToHide of document.getElementsByClassName(className)){eltsToHide.style.display='none'}}
function showByClass(className){for(eltsToHide of document.getElementsByClassName(className)){eltsToHide.style.display='block'}}
function generateUniqueID(){var d=new Date();var timer=d.toLocaleDateString().replace(/[/]/g,"")+"_"+d.toLocaleTimeString().replace(/[:]/g,"");id=myConfig.name+"_"+timer+document.getElementsByClassName("infos-perso")[0].value;return id}
function bAlert(message){return'<div class="alert alert-warning alert-dismissible" role="alert">'+'<strong>Erreur</strong> '+message+'<button type="button" class="close" data-dismiss="alert" aria-label="Close">'+'<span aria-hidden="true">&times;'+'</span></button></div>'}
function missingAlert(message){return'<div class="alert alert-info alert-dismissible" role="alert">'+'<strong>Fichier requis</strong> '+message+'<button type="button" class="close" data-dismiss="alert" aria-label="Close">'+'<span aria-hidden="true">&times;'+'</span></button></div>'}
function toSeconds(time){var a=time.split(':');var seconds=0;switch(a.length){case 1:seconds=time
break;case 2:seconds=(+a[0])*60+(+a[1]);break;case 3:seconds=(+a[0])*3600+(+a[1])*60+(+a[2]);break;default:alert("Heure du chapitre dans un format incorrect")
break}
return seconds}
function duration(from,to){return(to-from)/1000}
function toNum(n){if(n!=""){return n.toFixed(2).replace(".",",")}
return n}